### ISSUE TITLE
fit inconsistency of inference module

### ISSUE THREAD

**Issue by alyakin314** [neurodata/graspy#357] opened 2020-05-19 17:12 UTC
in order to be consistent with sklearn, as well as just general within graspy consistency, it would make more sense if fit methods of the tests were returning self instead of p value. it might also make sense to have fit_predict methods.

**Comment by bdpedigo** [comment] 2020-05-19 17:22
duplicate of #354

**Closed by bdpedigo** 2020-05-19 17:22 UTC
